### ISSUE TITLE
Handle non-zero exit of runner operation

### ISSUE THREAD

**Issue by webignition** [webignition/basil-runner#576]
The operation performed by a browser runner could return a non-zero exit code.

The non-zero exit code should not be output. An exception should instead be presented.

Snippet from output where the manifest contains a file that does not exist for the browser runner:

```yaml
---
type: test
path: /app/source/Test/003-form-page-test-chrome.yml
config:
  browser: chrome
  url: 'http://nginx/form.html'
...

100
```
